version: "2.4"
services:
  mockServer:
    image: mockserver/mockserver:mockserver-5.7.2
    ports:
      - 1080:1090
    environment:
      LOG_LEVEL: "DEBUG"
      SERVER_PORT: 1090
      PROXY_REMOTE_PORT: 80
      PROXY_REMOTE_HOST: www.mock-server.com
      JVM_OPTIONS: -Dmockserver.sslSubjectAlternativeNameDomains='org.mock-server.com,mock-server.com'