replicaCount: 1

app:
  logLevel: "INFO"
  serverPort: "1080"
  mapConfigDirectory: false
  initializationJsonFileName: "initializerJson.json"

image:
  repository: mockserver
  snapshot: false
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: NodePort
  port: 1080
  nodePort: ""

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - mockserver.local

podAnnotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
